apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hcp-idms-operator
  namespace: system
  labels:
    app: hcp-idms-operator
spec:
  selector:
    matchLabels:
      app: hcp-idms-operator
  template:
    metadata:
      labels:
        app: hcp-idms-operator
    spec:
      serviceAccountName: hcp-idms-operator
      containers:
      - name: manager
        image: quay.io/openshift/hcp-idms-operator:latest
        imagePullPolicy: Always
        command:
        - /manager
        args:
        - --leader-elect=false
        - --metrics-bind-address=0.0.0.0:8080
        - --health-probe-bind-address=0.0.0.0:8081
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "hcp-idms-operator"
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          fsGroup: 65532
        volumeMounts:
        - name: registry-config
          mountPath: /etc/containers/registry.conf.d
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: registry-config
        hostPath:
          path: /etc/containers/registry.conf.d
          type: DirectoryOrCreate
      - name: tmp
        emptyDir: {}
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      - operator: Exists
        effect: NoExecute
        key: node.kubernetes.io/not-ready
        tolerationSeconds: 300
      - operator: Exists
        effect: NoExecute
        key: node.kubernetes.io/unreachable
        tolerationSeconds: 300