apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hcp-idms-operator
  namespace: openshift-hcp-idms-operator
  labels:
    app: hcp-idms-operator
spec:
  selector:
    matchLabels:
      app: hcp-idms-operator
  template:
    metadata:
      labels:
        app: hcp-idms-operator
    spec:
      serviceAccountName: hcp-idms-operator
      initContainers:
      - name: setup-registry-dir
        image: registry.access.redhat.com/ubi8/ubi-minimal:latest
        command:
        - /bin/bash
        - -c
        - |
          mkdir -p /etc/containers/registry.conf.d
          chown -R 65532:65532 /etc/containers/registry.conf.d
          chmod -R 755 /etc/containers/registry.conf.d
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: registry-config
          mountPath: /etc/containers/registry.conf.d
      containers:
      - name: manager
        image: image-registry.openshift-image-registry.svc:5000/system/hcp-idms-operator:latest
        imagePullPolicy: Always
        command:
        - /manager
        args:
        - --leader-elect=false
        - --metrics-bind-address=0.0.0.0:8080
        - --health-probe-bind-address=0.0.0.0:8081
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "hcp-idms-operator"
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - SYS_ADMIN
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          fsGroup: 65532
        volumeMounts:
        - name: registry-config
          mountPath: /etc/containers/registry.conf.d
        - name: tmp
          mountPath: /tmp
        - name: sys
          mountPath: /sys
          readOnly: true
      volumes:
      - name: registry-config
        hostPath:
          path: /etc/containers/registry.conf.d
          type: DirectoryOrCreate
      - name: tmp
        emptyDir: {}
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      - operator: Exists
        effect: NoExecute
        key: node.kubernetes.io/not-ready
        tolerationSeconds: 300
      - operator: Exists
        effect: NoExecute
        key: node.kubernetes.io/unreachable
        tolerationSeconds: 300
